### ISSUE TITLE
Bug in project => TypeError: cb is not a function

### ISSUE THREAD

**Issue by ORESoftware** [npm/lockfile#23]
I just got this error

```
/home/olegzandr/Documents/WebstormProjects/poolio/node_modules/lockfile/lockfile.js:61
  fs.unlink(path, function (unlinkEr) { cb() })
                                        ^

TypeError: cb is not a function
    at /home/olegzandr/Documents/WebstormProjects/poolio/node_modules/lockfile/lockfile.js:61:41
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Looking at the code, looks like it's a bug
https://github.com/npm/lockfile/blob/master/lockfile.js

if the user doesn't pass a callback to lockFile.unlock, we will get the error

seems reasonable that the user might not want to handle any unlock errors,
so the user would just call

`lockFile.unlock(path);`

instead of

`lockFile.unlock(path, function(){});`

especially since there will never be an error present in the callback given the code,

I will submit a PR

**Comment by ORESoftware** [comment]
https://github.com/npm/lockfile/pull/24

**Comment by ORESoftware** [comment]
This PR was merged, so closing
